; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Eru Email Sender Pro"
#define MyAppVersion "2.0.0"
#define MyAppPublisher "EruStudio"
#define MyAppURL "https://jhudel.vercel.app/"
#define MyAppExeName "Eru Email Sender Pro.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{592E252E-31A6-4F27-A32F-DDC28CA7185E}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=C:\Users\Jhodel Orola\Downloads\New folder (2)\installer_output
OutputBaseFilename=mysetup
SetupIconFile=C:\Users\Jhodel Orola\Downloads\New folder (2)\EMAIL.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Jhodel Orola\Downloads\New folder (2)\dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Jhodel Orola\Downloads\New folder (2)\build\Eru Email Sender Pro\Analysis-00.toc"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Jhodel Orola\Downloads\New folder (2)\build\Eru Email Sender Pro\base_library.zip"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Jhodel Orola\Downloads\New folder (2)\build\Eru Email Sender Pro\Eru Email Sender Pro.pkg"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Jhodel Orola\Downloads\New folder (2)\build\Eru Email Sender Pro\EXE-00.toc"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Jhodel Orola\Downloads\New folder (2)\build\Eru Email Sender Pro\PKG-00.toc"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Jhodel Orola\Downloads\New folder (2)\build\Eru Email Sender Pro\PYZ-00.pyz"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Jhodel Orola\Downloads\New folder (2)\build\Eru Email Sender Pro\PYZ-00.toc"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Jhodel Orola\Downloads\New folder (2)\build\Eru Email Sender Pro\warn-Eru Email Sender Pro.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Jhodel Orola\Downloads\New folder (2)\build\Eru Email Sender Pro\xref-Eru Email Sender Pro.html"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

